from pathlib import Path

BASE_PATH = Path(__file__).parent

EXCEL_FILE = Path(r"C:\Users\pm28294\OneDrive - Alliance\VALE DIGITAL - PHF\REPORTE PHF MES ACTUAL V1.xlsm")

TEMPLATE_PATH = Path(r"C:\Users\pm28294\OneDrive - Alliance\TQM N1-Performance - Performance\2026\SEGUIMIENTO DIARIO FIPS\PHF\DASHBOARD - PHF\BENCH CVP - Archivos originales\dashboard_template.html")

OUTPUT_PATH = Path(r"C:\Users\pm28294\OneDrive - Alliance\TQM N1-Performance - Performance\2026\SEGUIMIENTO DIARIO FIPS\PHF\auto_phf_V1")

# HOJAS
SHEET_KPI_TOTAL = "PLOT EU_VH2"
SHEET_KPI = "PLOT EU_VH"
SHEET_PESOS = "PLOT REAL_K"
SHEET_CHART = "CIERRE MES"
SHEET_AVANCE = "PLOT_AVANCE"
SHEET_FAMILIAS = "PLOT FAMILIAS"
SHEET_FAMILIASDIA = "PLOT FAMILIASD-1"
SHEET_DIASTRABAJADOS = "PLOT DIAS TRABAJADOS"
SHEET_YTD = "PLOT YTD"
SHEET_APERTURADO = "PLOT_APERTURADO"
SHEET_FAM_APERTURADO = "PLOT FAM_APERTURADO"
SHEET_TGT_XCECO = "TGT_XCECO"
SHEET_JNT= "PLOT JNT"

# KPI TOTAL
COL_D1_TOTAL = "D-1"
COL_MTD_TOTAL = "MTD"
COL_YTD_TOTAL = "YTD"

# KPI
COL_DEPTO = "DEPARTAMENTO"
COL_D1 = "D-1"
COL_MTD = "MTD"
COL_YTD = "YTD"
COL_TGT = "TGT"
COL_GAP = "GAP VS TGT"

# PESOS
COL_DEPTO2 = "DEPARTAMENTO"
COL_REAL = "REAL K$"
COL_TARGET = "TARGET K$"
COL_BD_MES = "BD K$"
COL_ESTADO_TGT = "VS TGT %"
COL_ESTADO_BD = "VS BD %"


# AVANCE VOLUMEN
COL_AVANCE = "AVANCE"

# CHART
COL_MES = "MES"
COL_EUR_VH = "TOTAL EU/VH"

# FAMILIAS X DEPTO
COL_FAMILIAS = "FAMILIAS"
COL_DIRECCION = "01_DIR_26"
COL_EMBUTICION = "02_EMB_26"
COL_SOLDADURA = "03_SOL_26"
COL_PINTURA = "04_PIN_26"
COL_PARAGOLPES = "28_PGP_26"
COL_MONTAJE = "05_T&CVP_26"
COL_DLI = "07_DLI_26"
COL_MANTENIMIENTO = "08_MAN_26"
COL_CALIDAD = "09_CAL_26"
COL_GRL = "10_GRL_26"
COL_SERVICIOSRRHH = "11_SRH_26"
COL_CONTROLDEGESTION = "12_CGI_26"
COL_MONOZUKURI = "13_MZK_26"

# CHART DIAS TRABAJADOS
COL_DIA = "DIA"
COL_DIATRABAJADO = "DIAS TRABAJADOS"
COL_USINAXDIA = "USINA"

TARGET_LINE = 40

COLOR_OK = "darkgreen"
COLOR_BAD = "darkred"


# PLOT APERTURADO
COL_CECO = "CECO"
COL_DTO = "DTO"
COL_UET = "UET"


COL_AP_D1 = "D-1"
COL_AP_MTD = "MTD"
COL_AP_YTD = "YTD"
COL_AP_TGT_EUVH = "TGT EU/VH"

COL_AP_REAL_MTD = "REAL MTD"
COL_AP_TARGET_REAL = "TARGET REAL"
COL_AP_VS_BD = "VS BD"
COL_AP_VS_TGT = "VS TGT"
COL_AP_MTD_EU = "MTD EU"



# PESOS / $
COL_AP_REAL_MTD = "REAL MTD"
COL_AP_REAL_K = "REAL K$"
COL_AP_TARGET_K = "TARGET K$"
COL_AP_BD_MES="BD MES K$"
COL_AP_VS_BD = "VS BD%"
COL_AP_VS_TGT = "VS TGT%"

#jnt 

COL_D1_FB_JNT = "D-1 FAB/JNT"